// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ZQQ0BStH5drNiZ9UxFZWNKOKfgK0tIQ',
    appId: '1:332282545595:web:7c07e0f6c670f46792b09e',
    messagingSenderId: '332282545595',
    projectId: 'sutt-task-final',
    authDomain: 'sutt-task-final.firebaseapp.com',
    storageBucket: 'sutt-task-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_JemC_W-zSL-Yu8HXVnrvCIvMPN20AA',
    appId: '1:332282545595:android:4baba00ed8faa74f92b09e',
    messagingSenderId: '332282545595',
    projectId: 'sutt-task-final',
    storageBucket: 'sutt-task-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZK0VUia_obj0V03Tl-tXGnZZsaQh9hk',
    appId: '1:332282545595:ios:418d6e3a3998390792b09e',
    messagingSenderId: '332282545595',
    projectId: 'sutt-task-final',
    storageBucket: 'sutt-task-final.appspot.com',
    iosClientId: '332282545595-u6t8mia2j7lnasm9cg24ti8smv6l11ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.suttTaskFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZK0VUia_obj0V03Tl-tXGnZZsaQh9hk',
    appId: '1:332282545595:ios:5a675942aade2afe92b09e',
    messagingSenderId: '332282545595',
    projectId: 'sutt-task-final',
    storageBucket: 'sutt-task-final.appspot.com',
    iosClientId: '332282545595-e7j19jrlj7ipi6spe1uaroclpuuhhafa.apps.googleusercontent.com',
    iosBundleId: 'com.example.suttTaskFinal.RunnerTests',
  );
}
